---
# MegaLinter GitHub Action configuration file
# More info at https://megalinter.io
name: MegaLinter

on:
  push:
    branches: ["main"]  # run only when merge with main branch
  pull_request:
    branches: ["main"]  # run only when merge with main branch
  workflow_dispatch: {}

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    name: MegaLinter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Generate CZICompress_Config.h
        run: |
          mkdir -p .megalinter-config/include
          cat <<'EOF' > .megalinter-config/include/CZICompress_Config.h
#pragma once

#define CZICOMPRESS_UNIX_ENVIRONMENT 1 
#define CZICOMPRESS_WIN32_ENVIRONMENT 0 

#define CZICOMPRESS_VERSION_MAJOR u8"0" 
#define CZICOMPRESS_VERSION_MINOR u8"0" 
#define CZICOMPRESS_VERSION_PATCH u8"0" 
#define CZICOMPRESS_VERSION_TWEAK u8"0" 
#define CZICOMPRESS_VERSION_PATCH_STR u8"0" 

#ifdef NDEBUG
#define CZICOMPRESS_VERSION_TWEAK_STR u8"0" 
#else
#define CZICOMPRESS_VERSION_TWEAK_STR u8"0-DEBUG" 
#endif
EOF

      # MegaLinter
      - name: MegaLinter
        id: ml
        # You can override MegaLinter flavor used to have faster performances
        # More info at https://megalinter.io/flavors/
        uses: oxsecurity/megalinter/flavors/dotnet@v8
        env:
          # All available variables are described in documentation
          # https://megalinter.io/configuration/
          VALIDATE_ALL_CODEBASE: true
          CPP_CPPCHECK_ARGUMENTS: >
            --language=c++
            --std=c++17
            -I.megalinter-config/include

      # Upload MegaLinter artifacts
      - name: Archive production artifacts
        if: ${{ success() || failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: MegaLinter reports
          path: |
            megalinter-reports
            mega-linter.log
